---

- name: logrotate configuration for syslog files
  template:
    src: 'syslog.j2'
    dest: '{{ logs_logrotate_d_dir }}/syslog'
    owner: root
    group: root
    mode: 0644

- name: logrotate configuration for package manager files
  template:
    src: 'package_manager.j2'
    dest: '{{ logs_logrotate_d_dir }}/yum'
    owner: root
    group: root
    mode: 0644
